In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [21]:
dataset = pd.read_csv('ex1data2.txt', header = None )
mean = dataset.mean()[2]
stddev = dataset.std()[2]
data = (dataset - dataset.mean())/dataset.std()
data.head()

0         1         2
0  0.130010 -0.223675  0.475747
1 -0.504190 -0.223675 -0.084074
2  0.502476 -0.223675  0.228626
3 -0.735723 -1.537767 -0.867025
4  1.257476  1.090417  1.595389

In [0]:
# Separate out the Feature and Target matrices
data=np.asarray(data)
X=data[:,0:2]
Y=data[:,2:]
one = np.ones(len(X))
one = [one]
one = np.asarray(one)
X = np.concatenate((one.T,X),axis=1)
split = int(.8 * X.shape[0])
X_test = X[split+1:,:]
X = X[:split+1, :]
Y_test = Y[split+1:,:]
Y = Y[:split+1, :]

In [0]:
def computeCost(X,y,theta):
    tobesummed = np.power(((X.dot(theta.T))-y),2)
    return np.sum(tobesummed)/(2 * len(X))

In [0]:
def denormalise_price(price):
    global mean
    global stddev
    ret = price * stddev + mean
    return ret

In [0]:
def computeError(predicted, actual):
    error = 0
    for i in range(len(predicted)):
        error += abs(actual[i] - predicted[i]) / actual[i]
    error /= len(actual)
    return error[0]*100

In [26]:
#Applying Normal Equation
theta_norm = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(Y)
print("The parameters of Linear Regression are : ")
print(theta_norm.T)

finalCost_norm = computeCost(X,Y,theta_norm.T)
print("Cost after applying Normal Equation : ",finalCost_norm)

Y_pred = X_test.dot(theta_norm)
error = computeError(denormalise_price(Y_pred),denormalise_price(Y_test))
print('error percentage : ', error)
finalP_pred = denormalise_price(Y_pred)
print("predicted prices -")
print(finalP_pred)
print("actual prices -")
print(denormalise_price(Y_test))

The parameters of Linear Regression are : 
[[ 0.03961013  0.96637569 -0.00946032]]
Cost after applying Normal Equation :  0.12657643813551941
error percentage :  18.617875813699946
predicted prices -
[[680765.71998531]
 [368604.41822534]
 [295991.80040813]
 [381714.77910338]
 [430185.19134408]
 [223885.53836941]
 [172526.15158734]
 [321468.51781346]
 [224341.69224436]]
actual prices -
[[549000.]
 [287000.]
 [368500.]
 [329900.]
 [314000.]
 [299000.]
 [179900.]
 [299900.]
 [239500.]]
