In [0]:
import pandas as pd
import numpy as np
from scipy.spatial import distance

In [0]:
dataset=pd.read_csv(r'Absenteeism_at_work.csv')

In [0]:
dataset

ID  Reason for absence  ...  Body mass index  Absenteeism time in hours
0    11                  26  ...               30                          4
1    36                   0  ...               31                          0
2     3                  23  ...               31                          2
3     7                   7  ...               24                          4
4    11                  23  ...               30                          2
..   ..                 ...  ...              ...                        ...
735  11                  14  ...               30                          8
736   1                  11  ...               29                          4
737   4                   0  ...               34                          0
738   8                   0  ...               35                          0
739  35                   0  ...               25                          0

[740 rows x 21 columns]

In [0]:
dataset = np.array(dataset)

In [0]:
dataset

array([[ 11,  26,   7, ..., 172,  30,   4],
       [ 36,   0,   7, ..., 178,  31,   0],
       [  3,  23,   7, ..., 170,  31,   2],
       ...,
       [  4,   0,   0, ..., 170,  34,   0],
       [  8,   0,   0, ..., 170,  35,   0],
       [ 35,   0,   0, ..., 175,  25,   0]])

In [0]:
len(dataset[0])

21

In [0]:
len(dataset)

740

In [0]:
import numpy as np
import random

def kMedoids(D, k, tmax=100):
    # determine dimensions of distance matrix D
    m, n = D.shape

    # randomly initialize an array of k medoid indices
    M = np.sort(np.random.choice(n, k))

    # create a copy of the array of medoid indices
    Mnew = np.copy(M)

    # initialize a dictionary to represent clusters
    C = {}
    for t in range(tmax):
        # determine clusters, i. e. arrays of data indices
        J = np.argmin(D[:,M], axis=1)
        for kappa in range(k):
            C[kappa] = np.where(J==kappa)[0]
        # update cluster medoids
        for kappa in range(k):
            J = np.mean(D[np.ix_(C[kappa],C[kappa])],axis=1)
            j = np.argmin(J)
            Mnew[kappa] = C[kappa][j]
        np.sort(Mnew)
        # check for convergence
        if np.array_equal(M, Mnew):
            break
        M = np.copy(Mnew)
    else:
        # final update of cluster memberships
        J = np.argmin(D[:,M], axis=1)
        for kappa in range(k):
            C[kappa] = np.where(J==kappa)[0]

    # return results
    return M, C

In [0]:
from sklearn.metrics.pairwise import pairwise_distances
import numpy as np

data = dataset

# distance matrix
D = pairwise_distances(data, metric='euclidean')

# split into 2 clusters
M, C = kMedoids(D, 2)

print('medoids:')
for point_idx in M:
    print( data[point_idx] )

print('')
print('clustering result:')
for label in C:
    for point_idx in C[label]:
        print('label {0}:　{1}'.format(label, data[point_idx]))

medoids:
[    34     27      1      3      2    118     10     10     37 308593
     95      0      1      0      0      0      0     83    172     28
      2]
[    24     28      8      3      1    246     25     16     41 249797
     93      0      1      0      1      0      0     67    170     23
      4]

clustering result:
label 0:　[     3     23     11      5      4    179     51     18     38 306345
     93      0      1      0      1      0      0     89    170     31
      1]
label 0:　[    28     23     11      4      4    225     26      9     28 306345
     93      0      1      1      0      0      2     69    169     24
      1]
label 0:　[     3     13     11      5      4    179     51     18     38 306345
     93      0      1      0      1      0      0     89    170     31
      8]
label 0:　[    17     21     11      5      4    179     22     17     40 306345
     93      0      2      2      0      1      0     63    170     22
      8]
label 0:　[    15     23     1

In [0]:
meds = []
for point_idx in M:
    meds.append(data[point_idx]) 

In [0]:
#medoids
meds


[array([    34,     27,      1,      3,      2,    118,     10,     10,
            37, 308593,     95,      0,      1,      0,      0,      0,
             0,     83,    172,     28,      2]),
 array([    24,     28,      8,      3,      1,    246,     25,     16,
            41, 249797,     93,      0,      1,      0,      1,      0,
             0,     67,    170,     23,      4])]

In [0]:
clust1 = []
clust2 = []
for label in C:
    for point_idx in C[label]:
        if label == 0:
            clust1.append(data[point_idx])
        else:
            clust2.append(data[point_idx])

In [0]:
clust1

[array([     3,     23,     11,      5,      4,    179,     51,     18,
            38, 306345,     93,      0,      1,      0,      1,      0,
             0,     89,    170,     31,      1]),
 array([    28,     23,     11,      4,      4,    225,     26,      9,
            28, 306345,     93,      0,      1,      1,      0,      0,
             2,     69,    169,     24,      1]),
 array([     3,     13,     11,      5,      4,    179,     51,     18,
            38, 306345,     93,      0,      1,      0,      1,      0,
             0,     89,    170,     31,      8]),
 array([    17,     21,     11,      5,      4,    179,     22,     17,
            40, 306345,     93,      0,      2,      2,      0,      1,
             0,     63,    170,     22,      8]),
 array([    15,     23,     11,      5,      4,    291,     31,     12,
            40, 306345,     93,      0,      1,      1,      1,      0,
             1,     73,    171,     25,      5]),
 array([    14,     10,     11

In [0]:
len(clust1)

248

In [0]:
clust2

[array([    11,     26,      7,      3,      1,    289,     36,     13,
            33, 239554,     97,      0,      1,      2,      1,      0,
             1,     90,    172,     30,      4]),
 array([    36,      0,      7,      3,      1,    118,     13,     18,
            50, 239554,     97,      1,      1,      1,      1,      0,
             0,     98,    178,     31,      0]),
 array([     3,     23,      7,      4,      1,    179,     51,     18,
            38, 239554,     97,      0,      1,      0,      1,      0,
             0,     89,    170,     31,      2]),
 array([     7,      7,      7,      5,      1,    279,      5,     14,
            39, 239554,     97,      0,      1,      2,      1,      1,
             0,     68,    168,     24,      4]),
 array([    11,     23,      7,      5,      1,    289,     36,     13,
            33, 239554,     97,      0,      1,      2,      1,      0,
             1,     90,    172,     30,      2]),
 array([     3,     23,      7

In [0]:
len(clust2)

492

In [0]:
#squared error for first cluster
sse_1 = 0
for i in range(len(clust1[0])):
    sse_1 = sse_1 + np.square(distance.euclidean(meds[0],clust1[0][i]))

In [0]:
sse_1

3780720378621.0

In [0]:
#squared error for second cluster
sse_2 = 0
for i in range(len(clust2[0])):
    sse_2 = sse_2 + np.square(distance.euclidean(meds[1],clust2[1][i]))

In [0]:
sse_2

2395114312308.0005

In [0]:
#final squared error
sse = sse_1 + sse_2
sse

6175834690929.0